//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datatable.AzureSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public Nullable<double> Age { get; set; }
        public Nullable<double> Salary { get; set; }
        public int EmpId { get; set; }
    }
}
